# -*- coding: utf-8 -*-
"""Viento_geostrofico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14f47g7SR9xaA9yoFs7J2LQXCK_hewJSy
"""

# Parámetros iniciales

U_g = 15.81
R = 2000000
f_c = 1.028e-4

# Valor inicial para U_G

U_G = 1 # Could be U_g
tolerancia = 1e-9  # Criterio de convergencia
max_iter = 100000  # Número máximo de iteraciones

# Iteración
# Canviar el signo de la ecuación entre - ó + dependiendo de si es sistema ciclónico o anticiclónico

for i in range(max_iter):
    nuevo_U_G = U_g + ((U_G**2) / (R * f_c))

    # Check if nuevo_U_G is too large before assigning to U_G
    if nuevo_U_G > 1e100:  # Or another suitable threshold
        print("Divergencia: El valor de U_G se está volviendo demasiado grande.")
        break  # Exit the loop to prevent OverflowError

    #print(f"Diferencia {nuevo_U_G-U_G}") # Para ver los valores de diferencia


    if abs(nuevo_U_G - U_G) < tolerancia:  # Condición de convergencia
        break
    U_G = nuevo_U_G

# Resultado

print(f"Convergencia alcanzada después de {i+1} iteraciones: U_G = {U_G:.6f}")